#' Proprocess a trial results tibble
#'
#' This function takes a trial results tibble as generated by `read_study_data`
#' and adds a number of trial-level variables and summary statistics used for
#' quality checks and analyses. Assumes that `threat_appear_time` has already
#' been computed (as this can be study- and threat-specific)
#'
#' Requires the following columns:
#' `threat`, `scenario_data_0`, `head_movement_data_0`, `threat_movement_data_0`,
#' `end_state`, `fruittask0.csv_data_0`
#'
#' @param trials_raw A trial results tibble
#' @param buffer_time Time interval that recordings continue after trial ends (default: 1.5 s)
#' @param fade_time Time interval for fading the outcome display (default: 0.05 s)
#'
#' @returns
#' @export
#'
#' @examples
process_trial_results <- function(trials_raw,
                                  buffer_time = 1.5,
                                  fade_time = 0.05) {
  # eyetracker present?
  eyetracking <- "botheyes_eye_tracking_data_0" %in% colnames(trials_raw)
  saved_groups <- dplyr::groups(trials_raw) 

  # process results
  trial_results <- trials_raw %>%
    dplyr::mutate(threat = factor(threat),
                  end_display_time = end_time - buffer_time - fade_time) %>%
    dplyr::rowwise() %>%
    # positions
    dplyr::mutate(
      start_position = list(vrthreat::find_start_position(scenario_data_0)),
      initial_threat_position = list(vrthreat::find_initial_threat_position(scenario_data_0)),
      fruit_position = list(vrthreat::find_fruit_position(scenario_data_0)),
      safe_position = list(vrthreat::find_safe_position(scenario_data_0)),
    ) %>%
    # quality checks
    vrthreat::summarise_movement_cols() %>%
    vrthreat::check_tracker_cols(start_pos = "start_position") %>%
    dplyr::mutate(
      max_timestamp_duplicates = vrthreat::extract_timestamp_duplicates(head_movement_data_0)
    ) %>%
    # threat variables
    dplyr::mutate(
      threat_dist = 
        if (is.null(initial_threat_position) || is.null(fruit_position)) {
        NA_real_
      } else {
        vrthreat::calculate_2d_dist(
          initial_threat_position$pos_x,
          initial_threat_position$pos_z,
          fruit_position$pos_x,
          fruit_position$pos_z
        )
      },
      threat_dist_centre = vrthreat::extract_movement_dist(
        threat_movement_data_0,
        fruit_position,
        min_time = start_time + 0.5,
        max_time = start_time + 1
      )
    ) %>%
    # participant behaviour times
    dplyr::mutate(
      begin_escape_time = vrthreat::guess_move_from_pos(
        pos = fruit_position,
        ref_movement = head_movement_data_0,
        max_dist = 0.75,
        min_time = threat_appear_time,
        max_time = end_display_time
      ),
      end_escape_time = vrthreat::guess_escape_end_time(
        safe_pos = safe_position,
        max_time = end_display_time,
        end_state = end_state,
        ref_movement = head_movement_data_0
      ),
      escape_initiation_time =
        guess_escape_begin_time(
          head_movement_data_0,
          ref_pos = fruit_position,
          min_time = threat_appear_time,
          max_time = end_display_time
        ),
      begin_fruit_time = vrthreat::get_first_fruit_collection(fruittask0.csv_data_0),
      move_from_fruit_time = guess_move_from_pos(
        pos = fruit_position,
        ref_movement = head_movement_data_0,
        max_dist = 0.75,
        max_time = end_display_time
      ),
      move_from_start_time =
        guess_move_from_pos(
          pos = start_position,
          ref_movement = head_movement_data_0,
          max_dist = 0.75,
          max_time = end_display_time
        ),
      # participant behaviour summary statistics
      headdir_appear = extract_orientation2(
        head_movement_data_0,
        threat_movement_data_0,
        min_time = threat_appear_time,
        max_time = threat_appear_time + 1.5
      ),
      headdir_esc = extract_orientation2(
        head_movement_data_0,
        threat_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time
      ),
      bodydir_appear = extract_orientation2(
        waist_movement_data_0,
        threat_movement_data_0,
        min_time = threat_appear_time,
        max_time = threat_appear_time + 1.5
      ),
      bodydir_esc = extract_orientation2(
        waist_movement_data_0,
        threat_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time
      ),
      min_safe_dist = extract_movement_dist(
        head_movement_data_0,
        safe_position,
        min_time = start_time,
        max_time = end_display_time,
        method = "min"
      ),
      min_threat_dist_esc = extract_movement2_dist(
        head_movement_data_0,
        threat_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time,
        method = "min"
      ),
      fruit_picking_appear = extract_fruit_task(
        fruittask0.csv_data_0,
        min_time = threat_appear_time,
        max_time = threat_appear_time + 1.5,
        method = "rate"
      ),
      fruit_picking_before_esc = extract_fruit_task(
        fruittask0.csv_data_0,
        min_time = threat_appear_time,
        max_time = begin_escape_time,
        method = "rate"
      ),
      speed_peak_esc = extract_speed(
        head_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time,
        method = "max"
      ),
      speed_mean_esc = extract_speed(
        head_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time,
        method = "mean"
      ),
      scanpathspeed_head_before_fruit = extract_speed_angular(
        head_movement_data_0,
        min_time = start_time,
        max_time = begin_fruit_time,
        method = "mean",
        direction = c(0, 0, 1) # Forward gaze
      ),
      scanpathspeed_head_mean_appear = extract_speed_angular(
        head_movement_data_0,
        min_time = threat_appear_time,
        max_time = threat_appear_time + 1.5,
        method = "mean",
        direction = c(0, 0, 1) # Forward gaze
      ),
      scanpathspeed_head_mean_esc = extract_speed_angular(
        head_movement_data_0,
        min_time = begin_escape_time,
        max_time = end_escape_time,
        method = "mean",
        direction = c(0, 0, 1) # Forward gaze
      ),
      gaze_elevation_head_mean_appear = extract_gaze_elevation(
        head_movement_data_0,
        min_time = threat_appear_time,
        max_time = threat_appear_time + 1.5
      )
    ) %>%
    {
      if (eyetracking) {
        dplyr::mutate(
          .,
          scanpathspeed_eye_before_fruit = extract_speed_angular(
            botheyes_eye_tracking_data_0,
            min_time = start_time,
            max_time = begin_fruit_time,
            method = "mean",
            direction = c(0, 0, 1) # Forward gaze
          ),
          scanpathspeed_eye_mean_appear  = extract_speed_angular(
            botheyes_eye_tracking_data_0,
            min_time = threat_appear_time,
            max_time = threat_appear_time + 1.5,
            method = "mean",
            direction = c(0, 0, 1)
          ),
          scanpathspeed_eye_mean_esc  = extract_speed_angular(
            botheyes_eye_tracking_data_0,
            min_time = begin_escape_time,
            max_time = end_escape_time,
            method = "mean",
            direction = c(0, 0, 1)
          ),
          gaze_elevation_eye_appear = extract_gaze_elevation(
            botheyes_eye_tracking_data_0,
            min_time = threat_appear_time,
            max_time = threat_appear_time + 1.5
          ),
          headdir_fixation_appear = extract_fixation(
            botheyes_eye_tracking_data_0,
            find_unity_threat_name(scenario_data_0),
            min_time = threat_appear_time,
            max_time = threat_appear_time + 1.5
          ),
          headdir_fixation_esc = extract_fixation(
            botheyes_eye_tracking_data_0,
            find_unity_threat_name(scenario_data_0),
            min_time = begin_escape_time,
            max_time = end_escape_time
          )
        )
      } else {
        .
      }
    } %>%
    # aborted escape attempts
    dplyr::mutate(
      escape_aborted = guess_escape_abortion(
        waist_movement_data_0,
        safe_position,
        begin_escape_time,
        end_escape_time,
        end_state
      )
    ) %>%
    tidyr::unnest(escape_aborted, names_sep = "_") %>%
    dplyr::group_by(!!!saved_groups)
}
